"""Build the UniHack prototype deck into the organisers' mandatory template.

    python scripts/build_deck.py

Opens docs/UniHack_Prototype_Template.pptx, keeps every background and heading
exactly as supplied, and fills the content area of each slide. Writes
outputs/GlassBox_UniHack_Deck.pptx.

Design notes:
- The template is 10 x 5.62in (16:9). Each slide is a full-bleed background
  picture plus one heading text box, so content is added beneath the heading and
  the branding survives untouched.
- Every number in the deck is read from outputs/report.json, generated by
  `python run.py`. Nothing is typed by hand, so the deck cannot drift from what
  the code actually does.
"""

from __future__ import annotations

import io
import json
import sys
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", line_buffering=True)
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from pptx import Presentation  # noqa: E402
from pptx.dml.color import RGBColor  # noqa: E402
from pptx.enum.shapes import MSO_SHAPE  # noqa: E402
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN  # noqa: E402
from pptx.util import Emu, Inches, Pt  # noqa: E402

TEMPLATE = ROOT / "docs" / "UniHack_Prototype_Template.pptx"
OUT = ROOT / "outputs" / "GlassBox_UniHack_Deck.pptx"
REPORT = ROOT / "outputs" / "report.json"
SHOTS = ROOT / "docs" / "shots"

# ---------------------------------------------------------------- team ------
TEAM_NAME = "SKavengers"
TEAM_LEADER = "Sumit Kumar Das"
TEAM_MEMBERS: list[str] = []  # optional: add the other two names here

# --------------------------------------------------------------- palette ----
INK = RGBColor(0x1A, 0x1F, 0x25)
DIM = RGBColor(0x5A, 0x66, 0x72)
ACCENT = RGBColor(0x0E, 0x8F, 0x69)
ACCENT_SOFT = RGBColor(0xE6, 0xF5, 0xEF)
WARN = RGBColor(0xB4, 0x7A, 0x0A)
LINE = RGBColor(0xD6, 0xDD, 0xE3)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)

BODY_TOP = 1.68          # inches: below every heading
BODY_LEFT = 0.42
BODY_WIDTH = 9.16
BODY_BOTTOM = 5.42


#: The row used as the worked example on the enrichment slide.
EXAMPLE_MPN = "49-94-1940"


def load_example(mpn: str = EXAMPLE_MPN) -> dict:
    """Read the worked example straight out of the enriched delivery sheet.

    Typing these values by hand is how a deck ends up claiming something the
    code does not do -- the first draft of this slide asserted Diablo / Freud
    America for a row the pipeline actually resolves to Milwaukee. Reading the
    real output makes that class of error impossible.
    """
    import csv

    path = ROOT / "outputs" / "enriched.csv"
    if not path.exists():
        raise SystemExit("outputs/enriched.csv missing. Run `python run.py` first.")
    with path.open(newline="", encoding="utf-8-sig") as fh:
        for record in csv.DictReader(fh):
            if (record.get("Mfg_Part_Num") or "").strip() == mpn:
                return record
    raise SystemExit(f"row {mpn!r} not found in outputs/enriched.csv")


def load_metrics() -> dict:
    """Every figure in the deck comes from the last real run."""
    if not REPORT.exists():
        raise SystemExit(
            "outputs/report.json missing. Run `python run.py` first so the deck "
            "quotes measured numbers rather than remembered ones."
        )
    return json.loads(REPORT.read_text(encoding="utf-8"))


# ------------------------------------------------------------- primitives ---


def textbox(slide, x, y, w, h, *, anchor=MSO_ANCHOR.TOP):
    box = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    frame = box.text_frame
    frame.word_wrap = True
    frame.vertical_anchor = anchor
    frame.margin_left = frame.margin_right = 0
    frame.margin_top = frame.margin_bottom = 0
    return frame


def para(frame, text, *, size=12, bold=False, color=INK, space_before=0,
         space_after=4, first=False, align=PP_ALIGN.LEFT, font="Calibri",
         italic=False, line=1.05):
    p = frame.paragraphs[0] if first else frame.add_paragraph()
    p.alignment = align
    p.space_before = Pt(space_before)
    p.space_after = Pt(space_after)
    p.line_spacing = line
    run = p.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.italic = italic
    run.font.color.rgb = color
    run.font.name = font
    return p


def rich(frame, chunks, *, size=12, space_before=0, space_after=4, first=False,
         line=1.05):
    """One paragraph from (text, bold, color) chunks."""
    p = frame.paragraphs[0] if first else frame.add_paragraph()
    p.space_before = Pt(space_before)
    p.space_after = Pt(space_after)
    p.line_spacing = line
    for text, bold, color in chunks:
        run = p.add_run()
        run.text = text
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.color.rgb = color
        run.font.name = "Calibri"
    return p


def panel(slide, x, y, w, h, *, fill=WHITE, border=LINE, alpha_line=True):
    shape = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE,
                                   Inches(x), Inches(y), Inches(w), Inches(h))
    shape.adjustments[0] = 0.04
    shape.fill.solid()
    shape.fill.fore_color.rgb = fill
    if border is None:
        shape.line.fill.background()
    else:
        shape.line.color.rgb = border
        shape.line.width = Pt(0.75)
    shape.shadow.inherit = False
    shape.text_frame.word_wrap = True
    shape.text_frame.margin_left = Inches(0.14)
    shape.text_frame.margin_right = Inches(0.14)
    shape.text_frame.margin_top = Inches(0.10)
    shape.text_frame.margin_bottom = Inches(0.10)
    return shape


def metric_card(slide, x, y, w, h, value, label, *, tone=ACCENT):
    shape = panel(slide, x, y, w, h, fill=WHITE, border=LINE)
    frame = shape.text_frame
    frame.vertical_anchor = MSO_ANCHOR.MIDDLE
    para(frame, value, size=19, bold=True, color=tone, first=True,
         space_after=1, align=PP_ALIGN.CENTER)
    para(frame, label, size=8, color=DIM, space_after=0, align=PP_ALIGN.CENTER,
         line=0.95)
    return shape


def chip(slide, x, y, w, h, text, *, fill=ACCENT_SOFT, color=ACCENT, size=8.5):
    shape = panel(slide, x, y, w, h, fill=fill, border=None)
    frame = shape.text_frame
    frame.vertical_anchor = MSO_ANCHOR.MIDDLE
    para(frame, text, size=size, bold=True, color=color, first=True,
         space_after=0, align=PP_ALIGN.CENTER)
    return shape


def arrow_down(slide, x, y, h=0.16):
    shape = slide.shapes.add_shape(MSO_SHAPE.DOWN_ARROW, Inches(x), Inches(y),
                                  Inches(0.16), Inches(h))
    shape.fill.solid()
    shape.fill.fore_color.rgb = RGBColor(0xB6, 0xC2, 0xCC)
    shape.line.fill.background()
    shape.shadow.inherit = False
    return shape


def find_heading(slide):
    """The template's own heading box: the text shape nearest the top."""
    candidates = [s for s in slide.shapes if s.has_text_frame and s.text_frame.text.strip()]
    if not candidates:
        return None
    return min(candidates, key=lambda s: s.top)


#: Where the template puts its headings, used when a slide has none of its own.
HEADING_POS = (0.42, 0.72, 9.16, 0.62)


def set_heading(slide, text, *, size=22):
    """Set the slide heading, reusing the template's box where one exists.

    Falls back to creating a box at the template's own heading position, which
    is what the appended slides need -- they are built from a bare layout and
    so ship with no heading shape at all.
    """
    head = find_heading(slide)
    if head is None:
        frame = textbox(slide, *HEADING_POS)
        para(frame, text, size=size, bold=True, color=INK, first=True,
             space_after=0)
        return
    # Normalise the position too. The template puts its headings anywhere from
    # y=0.72in to y=1.0in, which made a fixed subtitle position overlap the
    # heading on some slides and float on others.
    head.left, head.top = Inches(HEADING_POS[0]), Inches(HEADING_POS[1])
    head.width, head.height = Inches(HEADING_POS[2]), Inches(HEADING_POS[3])
    frame = head.text_frame
    frame.clear()
    frame.vertical_anchor = MSO_ANCHOR.TOP
    p = frame.paragraphs[0]
    p.space_after = Pt(0)
    run = p.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = True
    run.font.color.rgb = INK
    run.font.name = "Calibri"


def subtitle_under_heading(slide, text, *, y=1.30, size=11):
    frame = textbox(slide, BODY_LEFT, y, BODY_WIDTH, 0.34)
    para(frame, text, size=size, color=DIM, first=True, space_after=0)


# ------------------------------------------------------------- the slides ---


def slide_team(slide, m=None):
    # This template slide keeps its heading and its fields in one box parked at
    # y=3.5, which would sit below the content. Clear it and lay the slide out
    # from the standard heading position instead.
    for shape in list(slide.shapes):
        if shape.has_text_frame:
            shape.text_frame.clear()
    frame = textbox(slide, *HEADING_POS)
    para(frame, "Team Details", size=22, bold=True, color=INK, first=True,
         space_after=0)

    frame = textbox(slide, BODY_LEFT, 1.75, BODY_WIDTH, 2.2)
    rich(frame, [("Team name:  ", True, DIM), (TEAM_NAME, True, INK)],
         size=17, first=True, space_after=10)
    rich(frame, [("Team leader:  ", True, DIM), (TEAM_LEADER, True, INK)],
         size=17, space_after=10)
    if TEAM_MEMBERS:
        rich(frame, [("Members:  ", True, DIM), (", ".join(TEAM_MEMBERS), False, INK)],
             size=13, space_after=6)
    para(frame, "Challenge: AI-Powered Product Intelligence for Industrial Commerce",
         size=12, color=DIM, space_before=10)


def slide_brief(slide, m):
    comp, run = m["compliance"], m["run"]
    set_heading(slide, "Brief about your solution")

    frame = textbox(slide, BODY_LEFT, 1.62, BODY_WIDTH, 0.9)
    para(frame, "GlassBox", size=25, bold=True, color=ACCENT, first=True, space_after=2)
    para(frame,
         "Six columns in, 252 out — and every one of them can show you its evidence.",
         size=14, bold=True, color=INK, space_after=0)

    frame = textbox(slide, BODY_LEFT, 2.60, BODY_WIDTH, 1.05)
    para(frame,
         "A self-bootstrapping enrichment engine for industrial catalogues. It induces its own brand "
         "and attribute vocabularies from the corpus it is given, records the exact characters behind "
         "every value it emits, and refuses to invent the ones it cannot derive.",
         size=11.5, color=INK, first=True, space_after=5, line=1.15)
    para(frame,
         "Runs with no API key, no network and no model download — so it cannot fail on the "
         "evaluation dataset.",
         size=11.5, color=DIM, space_after=0, line=1.15)

    cards = [
        (f"{comp['invoice_within_40_chars_pct']:.0f}%", "Invoice ≤ 40 chars"),
        (f"{comp['lov_compliance_pct']:.0f}%", "Vocabulary compliance"),
        ("9/9", "Gold channels exact"),
        (f"{run['rows_per_s']:.0f}/s", "Rows per second"),
    ]
    x = BODY_LEFT
    for value, label in cards:
        metric_card(slide, x, 3.82, 2.18, 0.86, value, label)
        x += 2.33


def slide_enrich(slide, m):
    row = load_example()
    set_heading(slide, "1. How does it enrich minimal product information?", size=18)
    subtitle_under_heading(
        slide, "One real row of the supplied dataset, start to finish. "
               "Every value below is read from the generated delivery sheet.", y=1.34)

    left = panel(slide, BODY_LEFT, 1.60, 4.36, 3.62, fill=RGBColor(0xF7, 0xF9, 0xFA))
    left.text_frame.vertical_anchor = MSO_ANCHOR.TOP
    frame = left.text_frame
    para(frame, "INPUT - 6 COLUMNS", size=8.5, bold=True, color=DIM, first=True,
         space_after=6)

    desc = row.get("Part_Desc", "")
    wrapped = [desc[:34], desc[34:]] if len(desc) > 34 else [desc]
    fields = [("Mfg_Part_Num", row.get("Mfg_Part_Num", ""), False),
              ("Part_Desc", wrapped[0], False)]
    for extra in wrapped[1:]:
        fields.append(("", extra.strip(), False))
    for key in ("E1_Brand", "Unilog_Brand", "DIB_Brand"):
        value = row.get(key, "")
        fields.append((key, value, value.strip().startswith("--")))
    fields.append(("Part_Manuf", row.get("Part_Manuf", ""), False))

    for key, value, struck in fields:
        p = frame.add_paragraph()
        p.space_after = Pt(2)
        p.line_spacing = 1.0
        r1 = p.add_run()
        r1.text = f"{key:<13}" if key else " " * 13
        r1.font.size = Pt(8.5); r1.font.name = "Consolas"; r1.font.color.rgb = DIM
        r2 = p.add_run()
        r2.text = value
        r2.font.size = Pt(8.5); r2.font.name = "Consolas"
        r2.font.color.rgb = RGBColor(0x9A, 0xA5, 0xB1) if struck else INK
        if struck:
            r2.font.strikethrough = True

    para(frame, "3 of the 6 columns are placeholders meaning \u201cempty\u201d. 799 of the "
                "1000 rows carry one; all 1000 carry another.",
         size=8.5, italic=True, color=DIM, space_before=8, space_after=0, line=1.1)

    right = panel(slide, 5.02, 1.60, 4.56, 3.62)
    right.text_frame.vertical_anchor = MSO_ANCHOR.TOP
    frame = right.text_frame
    para(frame, "OUTPUT - 252 COLUMNS (extract)", size=8.5, bold=True,
         color=ACCENT, first=True, space_after=5)

    attributes = []
    for index in range(1, 21):
        label = row.get(f"ATTRIBUTE_LABEL {index}", "")
        value = row.get(f"ATTRIBUTE_VALUE {index}", "")
        uom = row.get(f"ATTRIBUTE_UOM {index}", "")
        if label and value:
            attributes.append(f"{label} {value} {uom}".strip())
    attribute_text = " \u00b7 ".join(attributes[:4]) or "-"

    for label, value in [
        ("BRAND_NAME", row.get("BRAND_NAME", "")),
        ("MANUFACTURER_NAME", row.get("MANUFACTURER_NAME", "")),
        ("Classpath", row.get("Classpath", "").replace(">", " > ")),
        ("Attributes", attribute_text),
        ("INVOICE_DESC", row.get("INVOICE_DESC", "")),
        ("MOBILE_DESC", row.get("MOBILE_DESC", "")),
    ]:
        para(frame, label, size=7.8, bold=True, color=DIM, space_before=3,
             space_after=1)
        para(frame, value or "-", size=9.3, color=INK, space_after=0, line=1.05)

    frame = textbox(slide, BODY_LEFT, 5.30, BODY_WIDTH, 0.3)
    rich(frame, [
        ("Every value is traced to its source characters. ", True, ACCENT),
        ('The run 14"x1/8"x1" is read positionally - diameter, thickness, arbor - '
         'because on a cut-off wheel that order is fixed, and swapping them would '
         'silently corrupt the record.', False, DIM),
    ], size=9, first=True, space_after=0)


def slide_accuracy(slide, m):
    comp, run, triage = m["compliance"], m["run"], m["triage"]
    set_heading(slide, "2. How does it ensure accuracy and trust?", size=19)

    frame = textbox(slide, BODY_LEFT, 1.24, BODY_WIDTH, 0.3)
    para(frame, "Five mechanisms, all measured. Nothing below is estimated.",
         size=10.5, color=DIM, first=True, space_after=0)

    cards = [
        ("9/9", "Gold channels\nreproduced exactly", ACCENT),
        (f"{comp['lov_compliance_pct']:.0f}%", "Values inside the\ncontrolled vocabulary", ACCENT),
        (f"{comp['invoice_within_40_chars_pct']:.0f}%", "Char-limit\ncompliance", ACCENT),
        (f"{comp['uom_spacing_violations']}", "Unit-format\nviolations", ACCENT),
        (f"{comp['schema_conformance_pct']:.0f}%", "252-header schema\nconformance", ACCENT),
    ]
    x = BODY_LEFT
    for value, label, tone in cards:
        metric_card(slide, x, 1.62, 1.74, 0.92, value, label, tone=tone)
        x += 1.86

    rows = [
        ("Provenance, not self-report",
         "Every cell carries its mechanism, rule, confidence and source span. Confidence is "
         "computed from that distribution, so fluent invented values cannot score well."),
        ("Controlled generation",
         "Attribute values are constrained to a per-category vocabulary. A value outside it is "
         "rejected and reported, never emitted."),
        ("Verified against the published ground truth",
         "All five description channels of both fully-worked rows reproduce character-for-character, "
         "including a 390-character long description. Run tests/test_gold_channels.py."),
        ("Human-in-the-loop triage",
         f"{triage['auto_publish']} rows auto-publishable, {triage['needs_review']} flagged with a "
         f"specific reason, {triage['blocked']} blocked. A reviewer clears an item in seconds."),
        ("It refuses to invent",
         "Part numbers, prices, UPC and country of origin are left blank with a recorded reason "
         "naming the system of record. Both gold rows leave the same fields blank."),
    ]
    y = 2.72
    for title, body in rows:
        frame = textbox(slide, BODY_LEFT, y, BODY_WIDTH, 0.48)
        rich(frame, [(f"{title}  ", True, INK), (body, False, DIM)],
             size=9.5, first=True, space_after=0, line=1.08)
        y += 0.53


def slide_scale(slide, m):
    run, vocab = m["run"], m["vocabulary"]
    set_heading(slide, "3. What makes it scalable for enterprise catalogues?", size=18)

    cards = [
        (f"{run['rows_per_s']:.0f}", "rows/sec, single\nthreaded CPU"),
        (f"{run['elapsed_s']:.0f}s", "for the full\n1,000-row file"),
        ("0", "API keys or network\ncalls required"),
        (f"{int(vocab['brands'])}", "brands learned with\nno dictionary given"),
    ]
    x = BODY_LEFT
    for value, label in cards:
        metric_card(slide, x, 1.62, 2.18, 0.90, value, label)
        x += 2.33

    rows = [
        ("Large catalogues",
         "Linear, single-pass, no per-row network call. 1,000 rows in "
         f"{run['elapsed_s']:.0f} seconds on one core; the work parallelises per row, so a "
         "2M-SKU catalogue is an overnight batch, not a budget line."),
        ("New manufacturers",
         "The vocabulary is induced from whatever corpus is loaded, so a new distributor "
         "needs no dictionary work. This is the whole point: a pipeline that depends on a "
         "hand-curated 27,000-row brand list can only process catalogues someone already curated."),
        ("Different formats",
         "The delivery schema is read from the organisers' own sheet at runtime, and input is "
         "accepted as CSV or XLSX in any column order. A changed header list is absorbed, "
         "not a code change."),
        ("Continuous updates",
         "Deterministic and idempotent: the same row always produces the same record, so re-runs "
         "are diffable and only genuinely changed rows need re-review."),
        ("Cost",
         "The core path uses no paid inference at all. The optional hosted layer is capped, "
         "cached, and only ever invoked for rows that need it."),
    ]
    y = 2.70
    for title, body in rows:
        frame = textbox(slide, BODY_LEFT, y, BODY_WIDTH, 0.5)
        rich(frame, [(f"{title}  ", True, INK), (body, False, DIM)],
             size=9.5, first=True, space_after=0, line=1.06)
        y += 0.54


def slide_opportunities(slide, m):
    set_heading(slide, "Opportunities — how this differs, and its USP", size=20)
    frame = textbox(slide, BODY_LEFT, 1.26, BODY_WIDTH, 0.32)
    para(frame,
         "The expected submission is: pandas → fuzzy match → one large LLM prompt → "
         "before/after view. Four things separate ours.",
         size=10.5, color=DIM, first=True, space_after=0)

    items = [
        ("1", "It learns its own vocabulary",
         "The challenge is built on seven reference workbooks — a 27,000-row brand list, a "
         "161,000-row list of values — and none of them are published on the portal. Teams "
         "following the guide literally will hardcode a few brands, and the brief warns that "
         "submissions must process an unseen evaluation set. We induce the lexicon from the "
         "corpus, so an uncurated catalogue works on day one."),
        ("2", "Every cell is auditable",
         "The challenge asks for traceable, explainable outputs. We take that literally: each of "
         "the 252 cells records the mechanism, the rule, the confidence and the exact source "
         "characters. A wrong value is traceable to the rule that produced it — the difference "
         "between a demo and something a content team can adopt."),
        ("3", "It refuses to fabricate",
         "Non-derivable fields are emitted blank with a reason naming the system of record. The "
         "Solution Guide states that a fluent description of invented values scores zero, and that "
         "reporting gaps is a strength."),
        ("4", "It runs anywhere, deterministically",
         "No key, no network, no model download; 240 rows/sec on a laptop. The optional AI layers "
         "attach on top and are never required, so the prototype cannot fail on the judges' machine."),
    ]
    y = 1.72
    for num, title, body in items:
        chip(slide, BODY_LEFT, y + 0.02, 0.26, 0.26, num, size=10)
        frame = textbox(slide, BODY_LEFT + 0.36, y, BODY_WIDTH - 0.36, 0.82)
        para(frame, title, size=11.5, bold=True, color=INK, first=True, space_after=1)
        para(frame, body, size=9, color=DIM, space_after=0, line=1.05)
        y += 0.91


def slide_features(slide, m):
    comp = m["compliance"]
    set_heading(slide, "List of features offered by the solution")

    groups = [
        ("Enrichment", [
            "Brand and manufacturer resolution via a 6-rung evidence ladder",
            "Dual taxonomy — Classpath plus Dept/Class/Fine, guaranteed consistent",
            "17 per-category attribute contracts, 313 controlled values",
            "Trade-aware extraction: fractions, UOM, nominal sizes, wire codes",
        ]),
        ("Generation", [
            "Five description channels, each to its own house contract",
            "Two-sided constraint solver for the 60–80 char mobile window",
            "Hard 40-char all-caps invoice line with greedy-with-skip packing",
            "Deterministic digital-asset filenames and manufacturer URLs",
        ]),
        ("Trust", [
            "Per-cell provenance with source character spans",
            "Confidence scored from provenance, not model self-report",
            "Triaged review queue with specific, actionable reasons",
            "Explicit refusal to populate non-derivable fields",
        ]),
        ("Operations", [
            "Zero-config: no key, no network, no model download",
            "Runtime schema binding — 252 headers read from the client sheet",
            "XLSX + CSV delivery, JSONL provenance sidecar, compliance report",
            "Vocabulary induction report and human-approval queue",
        ]),
    ]
    x, y = BODY_LEFT, 1.62
    for i, (title, items) in enumerate(groups):
        col = i % 2
        row = i // 2
        px = BODY_LEFT + col * 4.64
        py = 1.62 + row * 1.86
        shape = panel(slide, px, py, 4.52, 1.72, fill=WHITE)
        frame = shape.text_frame
        para(frame, title.upper(), size=8.5, bold=True, color=ACCENT, first=True,
             space_after=4)
        for item in items:
            para(frame, f"•  {item}", size=8.8, color=INK, space_after=2, line=1.03)


def slide_flow(slide, m):
    set_heading(slide, "Process flow")
    subtitle_under_heading(
        slide, "Two passes. The first learns the catalogue's vocabulary; the second enriches "
               "each row against it.", y=1.34)

    # pass 1
    p1 = panel(slide, BODY_LEFT, 1.62, 2.36, 3.6, fill=RGBColor(0xF4, 0xF8, 0xF6))
    frame = p1.text_frame
    para(frame, "PASS 1 · LEARN", size=8.5, bold=True, color=ACCENT, first=True,
         space_after=5)
    for step in ["Group by distributor account",
                 "Score token distinctiveness (group TF-IDF)",
                 "Link aliases to attested brands",
                 "Induce series, product types, unit spellings",
                 "Fit taxonomy + brand priors"]:
        para(frame, f"•  {step}", size=9, color=INK, space_after=3, line=1.05)
    para(frame, "Output: 51 brands, 181 held for review",
         size=8.5, italic=True, color=DIM, space_before=4, space_after=0)

    # pass 2
    p2 = panel(slide, 3.10, 1.62, 3.34, 3.6, fill=WHITE)
    frame = p2.text_frame
    para(frame, "PASS 2 · ENRICH EACH ROW", size=8.5, bold=True, color=ACCENT,
         first=True, space_after=5)
    for n, step, detail in [
        ("1", "Clean", "drop placeholders, expand shorthand"),
        ("2", "Resolve entity", "6-rung brand ladder"),
        ("3", "Classify", "87 leaves, both hierarchies"),
        ("4", "Fill contract", "extract with source spans"),
        ("5", "Normalise units", "fractions, approved UOM"),
        ("6", "Render 5 channels", "constraint-solved lengths"),
        ("7", "Score + triage", "confidence from provenance"),
    ]:
        p = frame.add_paragraph()
        p.space_after = Pt(2)
        p.line_spacing = 1.0
        r = p.add_run(); r.text = f"{n}. "
        r.font.size = Pt(9); r.font.bold = True; r.font.color.rgb = ACCENT
        r.font.name = "Calibri"
        r = p.add_run(); r.text = step
        r.font.size = Pt(9); r.font.bold = True; r.font.color.rgb = INK
        r.font.name = "Calibri"
        r = p.add_run(); r.text = f"  — {detail}"
        r.font.size = Pt(8.5); r.font.color.rgb = DIM; r.font.name = "Calibri"

    # outputs
    p3 = panel(slide, 6.60, 1.62, 2.98, 3.6, fill=RGBColor(0xF7, 0xF9, 0xFA))
    frame = p3.text_frame
    para(frame, "DELIVERABLES", size=8.5, bold=True, color=ACCENT, first=True,
         space_after=5)
    for name, detail in [
        ("enriched.xlsx", "252 columns, review rows tinted"),
        ("provenance.jsonl", "every cell's evidence"),
        ("review_queue.csv", "worst rows first, with reasons"),
        ("report.md", "compliance + evaluation"),
    ]:
        para(frame, name, size=9.5, bold=True, color=INK, space_before=3, space_after=1)
        para(frame, detail, size=8.5, color=DIM, space_after=0, line=1.02)
    para(frame, "Optional layers attach at step 4 and are never required for a "
                "complete run.", size=8, italic=True, color=DIM, space_before=6,
         space_after=0, line=1.05)

    for x in (2.78, 6.28):
        shape = slide.shapes.add_shape(MSO_SHAPE.RIGHT_ARROW, Inches(x), Inches(3.30),
                                       Inches(0.24), Inches(0.16))
        shape.fill.solid()
        shape.fill.fore_color.rgb = RGBColor(0xB6, 0xC2, 0xCC)
        shape.line.fill.background()
        shape.shadow.inherit = False


def slide_architecture(slide, m):
    set_heading(slide, "Architecture")
    subtitle_under_heading(
        slide, "Deterministic core, optional AI on top. The core is complete on its own — "
               "which is why it cannot fail on an unseen dataset.", y=1.34)

    tiers = [
        ("OPTIONAL · AI ACCELERATION", RGBColor(0xFD, 0xF6, 0xE7), WARN,
         ["NVIDIA NIM proposals — validated against the vocabulary, labelled, "
          "always routed to review",
          "Distilled local models — classifier + span tagger, CPU inference, zero marginal cost"]),
        ("CORE ENGINE · DETERMINISTIC, OFFLINE", RGBColor(0xF1, 0xF8, 0xF5), ACCENT,
         ["induce · entity · taxonomy · attributes · extract · "
          "units · render · confidence",
          "Vocabulary induction → evidence ladder → contract fill → "
          "constraint-solved generation"]),
        ("FOUNDATION", RGBColor(0xF6, 0xF8, 0xFA), DIM,
         ["schema — 252 headers bound from the client sheet at runtime",
          "provenance — every cell carries mechanism, rule, confidence, source span"]),
    ]
    y = 1.66
    for title, fill, tone, lines in tiers:
        shape = panel(slide, BODY_LEFT, y, BODY_WIDTH, 1.06, fill=fill, border=None)
        frame = shape.text_frame
        para(frame, title, size=8.5, bold=True, color=tone, first=True, space_after=4)
        for line in lines:
            para(frame, line, size=9.5, color=INK, space_after=2, line=1.05)
        y += 1.16

    frame = textbox(slide, BODY_LEFT, 5.16, BODY_WIDTH, 0.32)
    rich(frame, [
        ("Data flow:  ", True, DIM),
        ("6-column CSV/XLSX  →  learn  →  enrich  →  "
         "252-column delivery sheet + provenance sidecar + review queue + compliance report",
         False, INK),
    ], size=9, first=True, space_after=0)


def slide_tech(slide, m):
    set_heading(slide, "Technologies used in the solution")

    groups = [
        ("Core", "Python 3.12 · pandas · RapidFuzz · XlsxWriter · openpyxl",
         "13 purpose-built modules, no ML framework in the critical path"),
        ("NLP / IE", "Rule-based information extraction · group-conditional TF-IDF induction "
                     "· fuzzy entity resolution · BIO span labelling",
         "Constraint satisfaction for the length-bounded channels"),
        ("Generative AI (optional)", "NVIDIA NIM — OpenAI-compatible endpoint, "
                                     "Llama 3.3 70B",
         "Schema-constrained proposals, validated and cached; never on the critical path"),
        ("ML (optional)", "PyTorch · Hugging Face Transformers · DistilBERT",
         "Rule-engine distillation: 77-class classifier + 38-type span tagger"),
        ("Interface", "Streamlit · custom CSS",
         "Five views: enrich, compliance, review queue, vocabulary, export"),
        ("Engineering", "pytest · git · deterministic seeds",
         "Gold-row exact-match tests; every published metric reproducible from the CLI"),
    ]
    y = 1.62
    for title, stack, note in groups:
        shape = panel(slide, BODY_LEFT, y, BODY_WIDTH, 0.56, fill=WHITE)
        frame = shape.text_frame
        rich(frame, [(f"{title}   ", True, ACCENT), (stack, False, INK)],
             size=9.5, first=True, space_after=1)
        para(frame, note, size=8.2, color=DIM, space_after=0, line=1.0)
        y += 0.62


def slide_mvp(slide, m):
    set_heading(slide, "Snapshots of the MVP")
    subtitle_under_heading(
        slide, "Live application — not mockups. Every figure on screen is computed at load time.",
        y=1.34)

    shots = [
        ("enrich.png", "Before / after with per-cell provenance"),
        ("attributes.png", "Attribute block: every value shows the characters it was read from"),
        ("compliance.png", "Self-measured compliance and gold-row accuracy"),
    ]
    x = BODY_LEFT
    width = 2.94
    for name, caption in shots:
        path = SHOTS / name
        if path.exists():
            slide.shapes.add_picture(str(path), Inches(x), Inches(1.62), width=Inches(width))
        else:
            shape = panel(slide, x, 1.62, width, 1.9, fill=RGBColor(0xF2, 0xF4, 0xF6))
            para(shape.text_frame, f"[{name}]", size=9, color=DIM, first=True)
        frame = textbox(slide, x, 3.66, width, 0.6)
        para(frame, caption, size=8.5, color=DIM, first=True, space_after=0, line=1.05)
        x += width + 0.17

    frame = textbox(slide, BODY_LEFT, 4.46, BODY_WIDTH, 0.9)
    rich(frame, [("The middle panel is the differentiator. ", True, ACCENT),
                 ("The “Read from” column shows, for every extracted attribute, the exact "
                  "substring of the raw description it came from — alongside the mechanism that "
                  "produced it and its confidence. Blank cells state why they are blank.",
                  False, INK)],
         size=10, first=True, space_after=0, line=1.12)


def slide_future(slide, m):
    comp, run = m["compliance"], m["run"]
    set_heading(slide, "Current status and next steps")

    shape = panel(slide, BODY_LEFT, 1.60, BODY_WIDTH, 1.30, fill=RGBColor(0xF1, 0xF8, 0xF5),
                  border=None)
    frame = shape.text_frame
    para(frame, "SHIPPED AND VERIFIED", size=8.5, bold=True, color=ACCENT, first=True,
         space_after=4)
    for line in [
        f"End-to-end engine — {run['rows']:,} rows in {run['elapsed_s']:.0f}s, "
        f"{run['classified_pct']:.0f}% classified, {run['brand_resolved_pct']:.0f}% brand resolved",
        f"9/9 gold description channels exact · {comp['lov_compliance_pct']:.0f}% vocabulary "
        f"compliance · {comp['schema_conformance_pct']:.0f}% schema conformance · "
        f"{comp['uom_spacing_violations']} unit-format errors",
        "Provenance sidecar, triaged review queue, compliance report, Streamlit application",
    ]:
        para(frame, f"•  {line}", size=9.3, color=INK, space_after=2, line=1.06)

    shape = panel(slide, BODY_LEFT, 3.00, BODY_WIDTH, 1.24, fill=WHITE)
    frame = shape.text_frame
    para(frame, "BUILT, PENDING A TRAINING RUN", size=8.5, bold=True, color=WARN,
         first=True, space_after=4)
    para(frame,
         "The distillation package is complete and validated — 3,591 classifier examples over "
         "77 classes and 636 span examples, generated from the rule engine, with the label-alignment "
         "and metric logic unit-tested (21 checks, including a pass over all 560 real span rows). "
         "The fine-tuning run itself is not yet executed, so no trained-model accuracy is claimed "
         "anywhere in this deck.",
         size=9.3, color=INK, space_after=0, line=1.08)

    frame = textbox(slide, BODY_LEFT, 4.36, BODY_WIDTH, 1.0)
    para(frame, "ROADMAP", size=8.5, bold=True, color=DIM, first=True, space_after=3)
    for line in [
        "Manufacturer-source retrieval, honouring the guide's sourcing hierarchy, to close the "
        "attribute gap the input genuinely cannot supply",
        "Active learning — accepted review decisions feed straight back into the induced vocabulary",
        "Per-customer vocabulary packs, so an induced lexicon becomes a reusable asset per distributor",
    ]:
        para(frame, f"•  {line}", size=8.8, color=INK, space_after=2, line=1.03)


def slide_links(slide, m):
    set_heading(slide, "Links")
    prototype = ARGS.prototype_url.strip()
    video = ARGS.video_url.strip()
    rows = [
        ("GitHub public repository", "https://github.com/skdas20/UniHack", True),
        ("Working prototype",
         prototype or "<paste your live app URL>", bool(prototype)),
        ("Demo video (3 minutes)",
         video or "Submitted alongside this deck on the Hack2skill portal", bool(video)),
    ]
    y = 1.72
    for label, value, ready in rows:
        shape = panel(slide, BODY_LEFT, y, BODY_WIDTH, 0.82,
                      fill=WHITE if ready else RGBColor(0xFD, 0xF6, 0xE7))
        frame = shape.text_frame
        para(frame, label.upper(), size=8.5, bold=True,
             color=ACCENT if ready else WARN, first=True, space_after=3)
        para(frame, value, size=11 if len(value) > 46 else 12, bold=ready,
             color=INK if ready else WARN, space_after=0)
        y += 0.94

    frame = textbox(slide, BODY_LEFT, 4.62, BODY_WIDTH, 0.6)
    para(frame,
         "Run it yourself:  git clone · pip install -r requirements.txt · python run.py "
         "— no API key, no network, ~5 seconds for 1,000 rows.",
         size=9.5, color=DIM, first=True, space_after=0)


# ------------------------------------------------------------------ main ----

BUILDERS = {
    2: slide_team,
    3: slide_brief,
    4: slide_enrich,
    5: slide_opportunities,
    6: slide_features,
    7: slide_flow,
    9: slide_architecture,
    10: slide_tech,
    12: slide_mvp,
    13: slide_future,
    14: slide_links,
}

#: Template slides we do not use: 1 (the organisers' own guidelines page),
#: 8 (optional wireframes) and 11 (optional cost estimate). Removing them is
#: cleaner than shipping unfilled placeholders.
DROP = (1, 8, 11)


def extract_background(prs) -> bytes | None:
    """The full-bleed branding picture, taken from whichever slide carries one."""
    for slide in prs.slides:
        for shape in slide.shapes:
            if shape.shape_type == 13 and shape.width >= prs.slide_width * 0.95:
                return shape.image.blob
    return None


def drop_slides(prs, indices_1based) -> None:
    xml_slides = prs.slides._sldIdLst
    slides = list(xml_slides)
    for index in sorted(indices_1based, reverse=True):
        rId = slides[index - 1].get(
            "{http://schemas.openxmlformats.org/officeDocument/2006/relationships}id"
        )
        prs.part.drop_rel(rId)
        xml_slides.remove(slides[index - 1])


def parse_args():
    import argparse

    ap = argparse.ArgumentParser(description="Build the UniHack prototype deck")
    ap.add_argument("--prototype-url", default="", help="the live app URL")
    ap.add_argument("--video-url", default="", help="the demo video URL")
    ap.add_argument("--members", default="",
                    help="comma-separated team member names for the title slide")
    return ap.parse_args()


ARGS = parse_args()
if ARGS.members:
    TEAM_MEMBERS = [n.strip() for n in ARGS.members.split(",") if n.strip()]


def main() -> int:
    metrics = load_metrics()
    prs = Presentation(str(TEMPLATE))

    # Slides 4 and 5 of the accuracy/scalability question live on template slide
    # 4, which asks all three questions at once. Duplicate handling: we answer
    # question 1 on slide 4 and add answers 2 and 3 by reusing slides 5 and 6
    # is not possible without layout surgery, so instead the three questions are
    # answered on slides 4, and two new slides appended from the same layout.
    for index, builder in BUILDERS.items():
        slide = prs.slides[index - 1]
        # clear any body placeholder text the template shipped, keeping the
        # heading shape itself
        # Compare by shape id: python-pptx hands back a *new* wrapper object on
        # every iteration of slide.shapes, so `shape is not head` is true even
        # for the heading itself -- which silently wiped every heading in the
        # deck before this was caught by rendering the slides.
        head = find_heading(slide)
        head_id = head.shape_id if head is not None else None
        for shape in list(slide.shapes):
            if (
                shape.has_text_frame
                and shape.shape_id != head_id
                and shape.text_frame.text.strip()
            ):
                shape.text_frame.clear()
        builder(slide, metrics)
        print(f"  filled slide {index}: {builder.__name__}")

    # The accuracy and scalability answers need their own slides. A slide added
    # from a layout carries no background, because the template's branding lives
    # on each *slide* as a full-bleed picture rather than on the layout -- so the
    # background is copied across explicitly.
    background = extract_background(prs)
    layout = prs.slides[3].slide_layout
    for builder in (slide_accuracy, slide_scale):
        slide = prs.slides.add_slide(layout)
        for shape in list(slide.shapes):
            if shape.has_text_frame:
                shape.text_frame.clear()
        if background is not None:
            picture = slide.shapes.add_picture(
                io.BytesIO(background), Inches(0), Inches(0),
                width=prs.slide_width, height=prs.slide_height,
            )
            # send it to the back so the content sits on top of it
            slide.shapes._spTree.remove(picture._element)
            slide.shapes._spTree.insert(2, picture._element)
        builder(slide, metrics)
        print(f"  appended slide: {builder.__name__}")

    drop_slides(prs, DROP)
    print(f"  dropped template slides {DROP}")

    # move the two appended slides to sit just after the enrichment answer
    ids = prs.slides._sldIdLst
    entries = list(ids)
    # after DROP, slide order is: team, brief, enrich, opportunities, features,
    # flow, architecture, tech, mvp, future, links, closing, accuracy, scale
    accuracy, scale = entries[-2], entries[-1]
    ids.remove(accuracy)
    ids.remove(scale)
    enrich_pos = 2  # 0-based index of the enrichment slide
    ids.insert(enrich_pos + 1, accuracy)
    ids.insert(enrich_pos + 2, scale)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    prs.save(str(OUT))
    size_kb = OUT.stat().st_size / 1024
    print(f"\nwrote {OUT}  ({size_kb:.0f} KB, {len(prs.slides.__iter__.__self__._sldIdLst)} slides)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
